# -*- coding: utf-8 -*-
"""PyTest Documents - Kacy Tran.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gy52S0T0td-h_G4P2Fzb_tPP4-jWqY9I
"""

class Testing:
    def __init__(self, edges) -> None:
        self.edges = edges
        self.simple_paths = []
        self.prime_paths = []
        self.relationship = {}
        self.make_relationship()

    def make_relationship(self):
        for edge in self.edges:
            f = edge[0]
            t = edge[1]
            if f not in self.relationship:
                self.relationship[f] = []
            self.relationship[f].append(t)
            if t not in self.relationship:
                self.relationship[t] = []

    def get_relationship(self):
        print("Relationship:", self.relationship)

    def find_paths(self):
        if self.simple_paths:
            return [self.simple_paths, self.prime_paths]
        else:
            for start_node in self.relationship.keys():
                visited = set()
                self.dfs_simple_paths(start_node, "", visited)

            self.find_prime_paths()
            return [self.simple_paths, self.prime_paths]

    def dfs_simple_paths(self, node, current_path, visited):
        current_path += str(node)
        visited.add(node)

        if node not in self.relationship or not self.relationship[node]:
            self.simple_paths.append(current_path+"!")
            return
        else:
            self.simple_paths.append(current_path)
            for neighbor in self.relationship[node]:
                if neighbor not in visited:
                    self.dfs_simple_paths(neighbor, current_path, visited.copy())
                else:
                    if str(neighbor) == current_path[0]:
                        self.simple_paths.append(current_path+str(neighbor)+"*")
                    else:
                        if str(neighbor) != current_path[-1]:
                            self.simple_paths[-1] = current_path + "!"

    def find_prime_paths(self):
        for sp in self.simple_paths:
            if sp[-1] == "*":
                self.prime_paths.append(sp)

        terminating = []
        for path in self.simple_paths:
            if path[-1] == "!":
                terminating.append(path)

        for i in range(len(terminating)):
            curr = terminating[i][:-1]
            found = False
            for j in range(len(terminating)):
                check = terminating[j][:-1]
                if i != j and len(curr) < len(check):
                    if check.find(curr) != -1:
                        found = True
                        break
            if not found:
                self.prime_paths.append(curr+"!")

    def return_paths(self):
        print("Simple Paths:", self.simple_paths)
        print("Prime Paths:", self.prime_paths)
        print("Summary -> Simple:", len(self.simple_paths), "| Prime:", len(self.prime_paths))

def validate_graph(edges):
    if not edges:
        raise ValueError("Empty graph")

    nodes = set()
    has_init = False
    has_term = False

    for u, v in edges:
        nodes.add(u)
        nodes.add(v)
        if u == "INIT":
            has_init = True
        if v == "TERM":
            has_term = True

    if not has_init:
        raise ValueError("Missing INIT node")
    if not has_term:
        raise ValueError("Missing TERM node")

    reachable = set()
    stack = ["INIT"]

    while stack:
        curr = stack.pop()
        if curr not in reachable:
            reachable.add(curr)
            for u, v in edges:
                if u == curr:
                    stack.append(v)

    if "TERM" not in reachable:
        raise ValueError("No path from INIT to TERM")

def v_g(e):
    if not e:
        raise ValueError("Empty graph")

    nd = set()
    has_i = False
    has_t = False

    for u, v in e:
        nd.add(u)
        nd.add(v)
        if u == "INIT":
            has_i = True
        if v == "TERM":
            has_t = True

    if not has_i:
        raise ValueError("Missing INIT")
    if not has_t:
        raise ValueError("Missing TERM")

    vis = set()
    st = ["INIT"]

    while st:
        cur = st.pop()
        if cur not in vis:
            vis.add(cur)
            for u, v in e:
                if u == cur:
                    st.append(v)

    if "TERM" not in vis:
        raise ValueError("No path INIT → TERM")


def run_test_cases():
    tc = [
        ("TC1 Empty List", [], True),

        ("TC2 [1,1,N,0,1]",
         [["INIT", "N"], ["N", "TERM"]], False),

        ("TC3 Self Loop",
         [["INIT", "N"], ["N", "N"], ["N", "TERM"]], False),

        ("TC4 Cycle",
         [["INIT","N1"],["N1","N2"],["N2","N3"],["N3","N4"],["N4","N2"],["N2","TERM"]],
         False),

        ("TC5 No INIT/TERM",
         [["N","N"]], True),

        ("TC6 Duplicate Loop",
         [["INIT","N1"],["N1","N5"],["N5","N5"],["N5","N7"],["N7","TERM"]],
         False),

        ("TC7 Multiple INIT",
         [["INIT","N1"],["N1","N3"],["INIT","N2"],["N2","N3"],["N3","TERM"]],
         False),

        ("TC8 Multiple TERM",
         [["INIT","N1"],["N1","N2"],["N2","N4"],["N1","N3"],["N3","TERM"],["N4","TERM"]],
         False),

        ("TC9 Disconnected",
         [["INIT","A"],["A","B"],["C","D"],["D","C"]],
         True),

        ("TC10 No Path to TERM",
         [["INIT","N1"],["INIT","N2"],["N1","TERM"]],
         True),

        ("TC11 Infinite Self Loop",
         [["INIT","N"],["N","N"]],
         True),

        ("TC12 Cycle No TERM",
         [["INIT","N1"],["N1","N2"],["N2","N1"]],
         True),

        ("TC13 Broken Chain",
         [["INIT","N1"],["N2","TERM"]],
         True),
    ]

    for n, e, err in tc:
        print(n)

        try:
            v_g(e)

            t = Testing(e)
            t.get_relationship()
            t.find_paths()
            t.return_paths()

            print("Passed" if not err else "Expected ERROR but passed")

        except Exception as ex:
            print("Correct ERROR:" if err else "Unexpected ERROR:", str(ex))


run_test_cases()